import CustomConsole from "../../utils/customConsole";

export default{
  Query: {
    
  },
  Mutation: {
    insertDataPoliticalParty: async (_, args, { models }) => {
      const checkStatus = await models.PoliticalParty.findAll();
      
      if(checkStatus.length>0){
        return false;
        //await models.PoliticalParty.destroy({where: {}, transaction: t });
      }

      const t = await models.sequelize.transaction();
      
      try {
        const inpPoliticalParty = [
          {name:'MVR', iso: ''},
          {name:'MAS', iso: ''},
          {name:'PCV', iso: ''},
          {name:'SI', iso: ''},
          {name:'IPCN', iso: ''},
          {name:'AA', iso: ''},
          {name:'MEP', iso: ''},
          {name:'GE', iso: ''},
          {name:'NRD', iso: ''},
          {name:'PPT', iso: ''},
          {name:'VTV', iso: ''},
          {name:'FJAC', iso: ''},
          {name:'LCR', iso: ''},
          {name:'IZQUIERDA', iso: ''},
          {name:'MIN', iso: ''},
          {name:'MDD', iso: ''},
          {name:'BR', iso: ''},
          {name:'ENCUENTRO', iso: ''},
          {name:'MUD', iso: ''},
          {name:'M.P.J.', iso: ''},
          {name:'U.N.T.C.', iso: ''},
          {name:'VPA', iso: ''},
          {name:'UVIVZLA', iso: ''},
          {name:'MIN-UNIDAD', iso: ''},
          {name:'AP', iso: ''},
          {name:'UNPARVE', iso: ''},
          {name:'UNIDAD DR', iso: ''},
          {name:'VA PA LANTE', iso: ''},
          {name:'FDC', iso: ''},
          {name:'VP', iso: ''},
          {name:'MOVEV', iso: ''},
          {name:'MPV', iso: ''},
          {name:'FL', iso: ''},
          {name:'PROCOMUNIDAD', iso: ''},
          {name:'UNOE', iso: ''},
          {name:'MOVERSE', iso: ''},
          {name:'MCM', iso: ''},
          {name:'UPC', iso: ''},
          {name:'MI GATO', iso: ''},
          {name:'PODER LABORAL', iso: ''},
          {name:'PODEMOS', iso: ''},
          {name:'PVC', iso: ''},
          {name:'PROVEN', iso: ''},
          {name:'UPV', iso: ''},
          {name:'CLASE MEDIA REVOLUCIONARIA', iso: ''},
          {name:'MCGN', iso: ''},
          {name:'LIGA SOCIALISTA', iso: ''},
          {name:'ONDA', iso: ''},
          {name:'TUPAMARO', iso: ''},
          {name:'FACOBA', iso: ''},
          {name:'REDES', iso: ''},
          {name:'CRV', iso: ''},
          {name:'GENTE EMERGENTE', iso: ''},
          {name:'INDEPENDIENTES POR LA COMUNIDAD NACIONAL', iso: ''},
          {name:'MNI', iso: ''},
          {name:'UNION', iso: ''},
          {name:'MRP', iso: ''},
          {name:'-', iso: ''},
          {name:'VAR. T. VAL', iso: ''},
          {name:'TUPAMAROS', iso: ''},
          {name:'POVEN', iso: ''},
          {name:'PODEMOS', iso: ''},
          {name:'PCV', iso: ''},
          {name:'MEP', iso: ''},
          {name:'REDES', iso: ''},
          {name:'UPV', iso: ''},
          {name:'PODERMOS', iso: ''},
          {name:'ONDA', iso: ''},
          {name:'MCR', iso: ''},
          {name:'UNIOM', iso: ''},
          {name:'UNION', iso: ''},
          {name:'CRBV', iso: ''},
          {name:'TUMARO', iso: ''},
          {name:'PODES', iso: ''},
          {name:'Var. T. Val.', iso: ''},
          {name:'MRV', iso: ''},
          {name:'PDOEMOS', iso: ''},
          {name:'UN NUEVO TIEMPO', iso: ''},
          {name:'PRIMERO JUSTICIA', iso: ''},
          {name:'MIN UNIDAD', iso: ''},
          {name:'UNIDAD', iso: ''},
          {name:'ACCION AGROPECUARIA', iso: ''},
          {name:'APERTURA', iso: ''},
          {name:'CONSTRUTORES DE UN PAIS', iso: ''},
          {name:'COPEI', iso: ''},
          {name:'ELECTORES LIBRES', iso: ''},
          {name:'FUERZA LIBERAL', iso: ''},
          {name:'FUERZA POPULAR', iso: ''},
          {name:'IMAGEN DEMOCRATICA', iso: ''},
          {name:'INDEPENDIENTES POR VENEZUELA', iso: ''},
          {name:'MOVIENTO LABORISTA', iso: ''},
          {name:'PPI', iso: ''},
          {name:'RENACE', iso: ''},
          {name:'VENEZUELA SOMOS TODOS', iso: ''},
          {name:'MR', iso: ''},
          {name:'UN SOLO PUEBLO', iso: ''},
          {name:'URD', iso: ''},
          {name:'POR QUERER A LA CIUDAD', iso: ''},
          {name:'DIGNIDAD PATRIOTICA', iso: ''},
          {name:'LA CAUSA R', iso: ''},
          {name:'VDP', iso: ''},
          {name:'VISION EMERGENTE', iso: ''},
          {name:'CONVERGENCIA', iso: ''},
          {name:'ONI', iso: ''},
          {name:'POLO DEMOCRATICO', iso: ''},
          {name:'IZQUIERDA DEMOCRATICA', iso: ''},
          {name:'LA LLAMA DE VENEZUELA', iso: ''},
          {name:'ENCUENTRO NACIONAL', iso: ''},
          {name:'NED', iso: ''},
          {name:'SOLUCION', iso: ''},
          {name:'AME', iso: ''},
          {name:'DR', iso: ''},
          {name:'PENSAMIENTO NACIONAL', iso: ''},
          {name:'FG', iso: ''},
          {name:'INDEPENDIENTE CON VISION DE FUTURO', iso: ''},
          {name:'PIEDRA', iso: ''},
          {name:'SOLIDARIDAD', iso: ''},
          {name:'VENEZUELA DE PRIMERO', iso: ''},
          {name:'ML', iso: ''},
          {name:'INDEPENDIENTES CON VISION DE FUTURO', iso: ''},
          {name:'IPV', iso: ''},
          {name:'MAS', iso: ''},
          {name:'VISION VENEZUELA', iso: ''},
          {name:'BANDERA ROJA', iso: ''},
          {name:'VENEZUELA DE PRIMERA', iso: ''},
          {name:'COPEI UNIDAD', iso: ''},
          {name:'PPI', iso: ''},
          {name:'VENZUELA DE PRIMERA', iso: ''},
          {name:'SIN RESULTADO', iso: ''},
          {name:'ONI', iso: ''},
          {name:'AME', iso: ''},
          {name:'SI', iso: ''},
          {name:'SOLIRIDARIDAD', iso: ''},
          {name:'COPEI', iso: ''},
          {name:'APERTURA', iso: ''},
          {name:'RANACE', iso: ''},
          {name:'POLO', iso: ''},
          {name:'SOLUCION', iso: ''},
          {name:'PIEDRA', iso: ''},
          {name:'Var. T. Val', iso: ''},
          {name:'FG', iso: ''},
          {name:'VISION VENEZUELA', iso: ''},
          {name:'IPV', iso: ''},
          {name:'CONVERGENCIA', iso: ''},
          {name:'MR', iso: ''},
          {name:'MOVIMIENTO REPUBLICANO', iso: ''},
          {name:'UNION REPUBLICANA DEMOCRATICA', iso: ''},
          {name:'FUERZA DE LA GENTE', iso: ''},
          {name:'DEMOCRACIA RENOVADORA', iso: ''},
          {name:'VENEZUELA SOMOS TODOS', iso: ''},
          {name:'FUERZA LIBERAL', iso: ''},
          {name:'ML', iso: ''},
          {name:'RENACE', iso: ''},
          {name:'BANDERA ROJA', iso: ''},
          {name:'NED', iso: ''},
          {name:'VENEZUELA DE PRIMERA', iso: ''},
          {name:'LA CAUSA R', iso: ''},
          {name:'ECUENTRO NACIONAL', iso: ''},
          {name:'NO SOLO PUEBLO', iso: ''},
          {name:'FUERZA POPULAR', iso: ''},
          {name:'VISION VENZUELA', iso: ''},
          {name:'FUERZA NACIONAL', iso: ''},
          {name:'UN SOLO PUEBLO', iso: ''},
          {name:'SOLODARIDAD', iso: ''},
          {name:'U.R.D', iso: ''},
          {name:'FUERZA LIBRE', iso: ''},
          {name:'POR QUERER A LA CIUDAD', iso: ''},
          {name:'DIGNIDAD PATRIOTICA', iso: ''},
          {name:'CONSTRUCTORES DE UN PAIS', iso: ''},
          {name:'O.N.I', iso: ''},
          {name:'IZQUIERDA DEMOCRATICA', iso: ''},
          {name:'S.I', iso: ''},
          {name:'ENCUENTRO NACIONAL', iso: ''},
          {name:'I.N.C.V.F', iso: ''},
          {name:'PENSAMIENTO NACIONAL', iso: ''},
          {name:'UNIDAD', iso: ''},
          {name:'VISION EMERGENTE', iso: ''},
          {name:'PRIMERO JUSTICIA', iso: ''},
          {name:'VENEZUELA PRIMERA', iso: ''},
          {name:'VENEZUELA PRIMERA', iso: ''},
          {name:'RENCE', iso: ''},
          {name:'DEMOCRACIA RENOVADORA', iso: ''},
          {name:'INDEPENDIENTES CON VISION DE FUTURO', iso: ''},
          {name:'UNION REPUBLICANA DEMOCRATICA', iso: ''},
          {name:'DIGINIDA PATRIOTICA', iso: ''},
          {name:'FUERZA POPULA', iso: ''},
          {name:'VEZUELA SOMOS TODOS', iso: ''},
          {name:'DIGINIDAD PATRIOTICA', iso: ''},
          {name:'JOVEN', iso: ''},
          {name:'MLPU', iso: ''},
          {name:'HIJOS DE LA PATRIA', iso: ''},
          {name:'MOVIMIENTO DE CONCIENCIA DE PAIS', iso: ''},
          {name:'NUEVO ORDEN SOCIAL', iso: ''},
          {name:'IFP', iso: ''},
          {name:'INICIATIVA PROPIA', iso: ''},
          {name:'VTM', iso: ''},
          {name:'POR QUERER A VENEZUELA', iso: ''},
          {name:'ROMPAMOS CADENAS', iso: ''},
          {name:'MOVIMIENTO SENTIR NACIONAL', iso: ''},
          {name:'VTN', iso: ''},
          {name:'PSUV', iso: ''},
          {name:'P.C.V.', iso: ''},
          {name:'P.P.T.', iso: ''},
          {name:'NCR', iso: ''},
          {name:'PRT', iso: ''},
          {name:'UDEMO', iso: ''},
          {name:'ORA', iso: ''},
          {name:'PDUPL', iso: ''},
          {name:'PSL', iso: ''}
        ]
      
        await models.PoliticalParty.bulkCreate(inpPoliticalParty, { transaction: t });
        t.commit();
        return true;
      } catch (error) {
        CustomConsole({ origin: 'insertDataPoliticalParty', info: error})
        t.rollback();
        return false
      }
    },
  }
}